service: serverless-example

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: example/handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
