service: serverless-example-express

plugins:
  - serverless-plugin-typescript
  - serverless-domain-manager
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 128
  endpointType: regional
  environment:
    STAGE: ${opt:stage, 'dev'}

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

custom:
  customDomain:
    domainName: ${opt:stage, 'dev'}lambda.intelliwake.com
    basePath: ''
    stage: ${opt:stage, 'dev'}
    certificateArn: 'arn:aws:acm:us-east-1:074758340900:certificate/a7c3c67d-b72d-4b5e-914a-a014b7a0cf87'
    createRoute53Record: true
  serverless-offline:
    httpsProtocol: 'dev-certs'
    httpPort: 4000
    useChildProcesses: true
    stageVariables:
        STAGE: local
